<?xml version="1.0" ?><!DOCTYPE extension  PUBLIC '-//QM/2.3/Extension//EN'  'http://www.codesourcery.com/qm/dtds/2.3/-//qm/2.3/extension//en.dtd'>
<extension class="GaudiTest.GaudiExeTest" kind="test">
  <argument name="program"><text>gaudirun.py</text></argument>
  <argument name="timeout"><integer>1200</integer></argument>
  <argument name="args"><set>
    <text>$BRUNELROOT/tests/options/testBrunel-defaults.py</text>
    <text>$BRUNELOPTS/2009-Collisions.py</text>
    <text>--option</text>
    <text>from Configurables import (OutputStream, Brunel); Brunel().EvtMax=100; OutputStream("DstWriter").Output = "DATAFILE='PFN:Brunel-2009-fixed.dst' TYP='POOL_ROOTTREE' OPT='REC'"; </text>
  </set></argument>
  <argument name="timeout"><integer>3000</integer></argument>
  <argument name="use_temp_dir"><enumeral>true</enumeral></argument>
  <argument name="validator"><text>
from Brunel.QMTest.BrunelExclusions import preprocessor
#validateWithReference(preproc = preprocessor)
countErrorLines({"FATAL":0, "WARNING":0, "ERROR":2})
#"IODataManager       ERROR You may not be able to navigate back to the input file -- processing continues"
#"IODataManager       ERROR Referring to existing dataset root:/castor/cern.ch/grid/lhcb/data/2009/RAW/FULL/LHCb/COLLISION09/63497/063497_0000000001.raw by its physical name"
</text></argument>
</extension>
